#!/bin/csh -f

# RUN THE C PREPROCESSOR ON THE PREPARES SISAL SOURCE FILE AND LEAVE THE RESULT
# IN $3.i
# ARGUMENTS: $1=spp2 $2=cc_cmd $3=sisfile $4=result $5=rest

set spp2cmd=$1
set cccmd=$2
set sisfile=$3
set result=$4
shift;shift;shift;shift

set cfile = $result:r.c
set sppfile = $result:r.spp

if ( -e $cfile == 1 ) then
  if ( -w $cfile != 1 ) then
    echo cannot overwrite $cfile
    exit 1
  endif
endif
/bin/rm -f $cfile

if ( -e $sppfile == 1 ) then
  if ( -w $sppfile != 1 ) then
    echo cannot overwrite $sppfile
    exit 1
  endif
endif
/bin/rm -f $sppfile
  
if ( -e $sisfile != 1 ) then
  echo $sisfile does not exist
  exit 1
endif

/bin/cp $sisfile $cfile
if ( $status <> 0 ) then
  /bin/rm -f $cfile
  exit 1
endif

$cccmd -E -I. $* $cfile >! $sppfile
if ( $status != 0 ) then
  /bin/rm -f $cfile
  /bin/rm -f $sppfile
  exit 1
endif

$spp2cmd -B$cfile -R$sisfile < $sppfile >! $result
if ( $status != 0 ) then
  /bin/rm -f $sppfile
  /bin/rm -f $cfile
  exit(1)
endif

/bin/rm -f $sppfile
/bin/rm -f $cfile

exit 0
